FROM node:22-bookworm-slim AS frontend

WORKDIR /build
COPY client/package.json client/package-lock.json ./client/
RUN npm ci --prefix client
COPY client ./client
RUN npm run build --prefix client


FROM nginx:alpine
RUN rm -f /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh


COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend /build/client/dist /usr/share/nginx/html

EXPOSE 8080
